[package]
name = "route_utils"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
geo = { workspace = true }
log = { workspace = true }
common = { path = "../common" }